### ISSUE TITLE
JavaScript error when installing from web UI

### ISSUE THREAD

**Issue by bdeboe** [mwaseem75/DataSetProj#10]
I get the following JavaScript error when installing a dataset from the web page:

![image](https://user-images.githubusercontent.com/12095468/149317444-5fe0a814-7d76-49fd-a710-272386ff2a6e.png)

I'm pretty sure this is because of the `ImportDS()` method just writing directly to stdout, which CSP doesn't like. You may want to add a verbose flag to that method (and the one for removing a dataset) to avoid the JS error, or make it display this in a regular alert message that doesn't say "ERROR" when in fact it's all working fine :-)

**Comment by mwaseem75** [comment]
Thanks Benjamin for highlighting this point.
Although as you already stated it is not an error and application was working fine, Anyhow the JavaScript error is resolved now.
