### ISSUE TITLE
mismatch in "installed" status between sidebar and main dashboard contents

### ISSUE THREAD

**Issue by bdeboe** [mwaseem75/DataSetProj#11]
really a minor inconvenience: after installing a few datasets, some of them appear as installed in the main dashboard, but not in the sidebar. In the screenshot below, look at "Cancer rates by US state", which I didn't install by clicking it (yet!):

![image](https://user-images.githubusercontent.com/12095468/149318294-48adf54b-2bc5-4a2f-b3b1-1af47eba3033.png)

This may be because of overlapping table names between datasets, or some tiny typos / mismatch in the code checking the installed status between those two parts of the UI. Perhaps you can just store a flag somewhere based on dataset ID (which you pass to InstallDS()) and make the installation status more explicit.

**Comment by mwaseem75** [comment]
The shared snapshot is not stating any problem and status of sidebar and main dashboard is matching already.
Thanks

**Comment by bdeboe** [comment]
aaaaah, I was just looking at the colours and though green meant installed, which by sheer chance matched for the one in the line above that I looked at 😄 
Thanks for the clarification!
