### ISSUE TITLE
zpm install doesn't work

### ISSUE THREAD

**Issue by grongierisc** [mwaseem75/DataSetProj#7]
zpm install doesn't work on a other container than the one in this repository : 

irisowner@f3a4b8e63d46:/opt/irisapp$ iris session iris

Node: f3a4b8e63d46, Instance: IRIS

USER>zn "IRISAPP"

IRISAPP>zpm "install dataset-medical"

[dataset-medical]       Reload START (/usr/irissys/mgr/.modules/IRISAPP/dataset-medical/1.0.2/)
[dataset-medical]       Reload SUCCESS
[dataset-medical]       Module object refreshed.
[dataset-medical]       Validate START
[dataset-medical]       Validate SUCCESS
[dataset-medical]       Compile START
[dataset-medical]       Compile SUCCESS
[dataset-medical]       Activate START
[dataset-medical]       Configure START
[dataset-medical]       Configure FAILURE
[dataset-medical]       Activate FAILURE
ERROR! Directory name '/opt/irisapp/src/data/synthetic/' is invalid

Otherwise, great stuff + great ui

**Comment by mwaseem75** [comment]
ZPM issue is fixed.
Thanks
